### ISSUE TITLE
TestNet42-Peggy transfers failing with signature verification error due to incorrect CHAINID

### ISSUE THREAD

**Issue by sheokapr** [Sifchain/sifnode#1613]
In TestNet-42, peggy txn (from ethereum to sifchain) failed with this error- signature verification failed; please verify account number (7472) and chain-id (sifchain-testnet-1): unauthorized

datadog error log: https://app.datadoghq.com/logs?query=host%3Ai-0afd4cf7d28637d56%20service%3Aebrelayer[…]UE&viz=&from_ts=1626262164041&to_ts=1626264705469&live=false

_IM  11 minutes ago
The contracts are correct. The reason why the chain name is different is because this chain started as sifchain-testnet-042 and then it was forked, and became sifchain-testnet-1.

**Comment by lanerjo** [comment]
This should be resolved

 

From: Pradeep Sheokand ***@***.***>
Reply-To: Sifchain/sifnode ***@***.***>
Date: Wednesday, July 14, 2021 at 7:09 AM
To: Sifchain/sifnode ***@***.***>
Cc: Lance Zukel ***@***.***>, Assign ***@***.***>
Subject: Re: [Sifchain/sifnode] TestNet42-Peggy transfers failing with signature verification error due to incorrect CHAINID (#1613)

 

Assigned #1613 to @lanerjo.

**Comment by intl-man** [comment]
Closing as this has since been resolved.
