### ISSUE TITLE
Add Mapping of IbcToken to Polygon Assets

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1841]

**Comment by ElliotFriedman** [comment]
Instructions on what needs to be done https://sifchain.slack.com/archives/C01DZ17890D/p1630805049088400

Essentially we need to create new tokens on polygon, then map those tokens to the IbcTokens properly so that users can peg their IBC Tokens on ethereum onto polygon.

**Comment by daniportugalgit** [comment]
I'll bring the specs we received to this space so that we can have history on this ask.

> FYI, we'll need to verify Polygon Network token contracts after we launch these IBC tokens on Ethereum.  That way, people can use the Ethereum <> Polygon to use these assets in Polygon's DeFi ecosystem.  Instructions below:
> 1 - Deploy Token contract on Polygon (should have deposit and withdraw functionality)
> 2 - Verify contract on explorer.matic.network or polygonscan.com 
> 3 - Put in a mapping request on mapper.matic.today
> https://docs.matic.network/docs/develop/getting-started/

-----
I'll read the shared docs and see if I can understand everything that the sentence _"should have deposit and withdraw functionality"_ means. After reading the docs, I'll try and estimate the task, or ask for clarification.

**Comment by daniportugalgit** [comment]
Ok, I sent a test mapping first, using one of the incomplete deploys we had made last week. They say that remappings take up to 1 week to be fulfilled, so I thought it was better to test it first.

What I'm unsure of: Polygon says that there are requisites to do the mapping. One of them is "_The mint function on the root contract can only be called by the corresponding token PredicateProxyAddress_"

As I understand it, since we're mapping FROM Ethereum TO Polygon, we actually do not want Polygon to be able to mint our Ethereum tokens. Only the Polygon side should be mintable by their system because our users will LOCK tokens on the Ethereum side and receive minted tokens on the Polygon side. To go back, they will BURN tokens on the Polygon side, which will UNLOCK tokens on the Ethereum side.

Nevertheless, since the requisite was there, I decided to test it first. If it works, I'll finish the task by sending all the other tokens.

Tokens that will be mapped are the following:
ATOM: 0x8D983cb9388EaC77af0474fA441C4815500Cb7BB
KAVA: 0x0C356B7fD36a5357E5A017EF11887ba100C9AB76
AKT: 0xC727f87871ee12Bbcedd2973746D1Deb7529aaD6
ION: 0xee59B43149CEAD680aedF8778163ce8CB8c8A6fB
REGEN: 0xeEE10b3736d5978924f392ED67497cfAE795128B
OSMO: 0x93A62Ccfcf1EfCB5f60317981F71ed6Fb39F4BA2
HARD: 0x1C700F95Df53fc31e83D89AC89e5DD778D4cD310
XPRT: 0xae837EacBAE2a6bA166ce0DEd5C72340f212835c
IRIS: 0x76C4A2B59523eaE19594c630aAb43288dBB1463f

**Comment by daniportugalgit** [comment]
I opened a ticket at Polygon to clarify things. I'll wait until tomorrow to see if they answer us.

**Comment by pandaring2you** [comment]
super interesting. i didnt realize we needed to enable Cosmos->Sifchain->Ethereum->Polygon functionality as part of the IBC launch. is it not possible to move tokens from Sifchain to Polygon directly? 

cc @caseyturnerarrington - so he can follow along

**Comment by daniportugalgit** [comment]
Right now, we have 8 tokens mapped. Cosmos (ATOM) is missing and we're talking with Polygon's support to solve an issue with that submission.
