### ISSUE TITLE
Investigate debugging tools 

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1995]
please add details if it turns out to be a worthwhile task

**Comment by smartyalgo** [comment]
We are trying to launch a debugging instance from VS Code. It is currently defined in `launch.json` by passing in hard-coded args.

Due to VS Code's order of resolving & substituting variables, one cannot use environment variables in args.
https://code.visualstudio.com/docs/editor/variables-reference#_configuration-variables
> Variable substitution in debug configurations or tasks is a two pass process:
- In the first pass, all variables are evaluated to string results. If a variable occurs more than once, it is only evaluated once.
- In the second pass, all variables are substituted with the results from the first pass.

https://github.com/microsoft/vscode/issues/89825
according to the person from microsoft
> it can not pick up anything from an .env file that is processed after ${env:Name} has been substituted

He suggested writing a VS Code extension for this.

**Comment by pandaring2you** [comment]
Finished an alternate solution
