### ISSUE TITLE
Rowan symbol miss-matches

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#230]
Hey guys, 

I keep seeing Rowan symbol miss-matches in the code. ie from how handle the symbol in the smart contracts, peggy go code and  in clp. 

May I suggest we just use the following:

`rowan` in all places? 

@ElliotFriedman @Jedi2002 @jkbrooks @intl-man @AustinoBombino @musnit @ryardley @59023g 

Lets disucss here and come to consensus before making any changes?

**Comment by utx0** [comment]
And when a `rowan` assert is ported to etherum this will be `erowan`

**Comment by utx0** [comment]
Let me know if there are any issues with my suggestion.

**Comment by juniuszhou** [comment]
Peggy go code just read the symbol from message and add/remove prefix like 'c' 'e'. Rowan is nothing special for peggy. I think we need keep consistent between erc20 smart contract's symbol and sifchain native token name.

**Comment by ElliotFriedman** [comment]
My understanding is that 'c' means an ethereum native asset that is pegged and on top of sifchain
'e' means a cosmos native asset that is created on top of ethereum through peggy.

My source is looking at the cosmos bridge file.

Rowan can have the symbol Rowan, however when we store it in the smart contracts, we are going to store the symbol for prophecies as eRowan because it is a cosmos native asset on top of ethereum.

**Comment by Jedi2002** [comment]
I agree , we should have uniformity . 

- I would suggest , we can add the native token to the genesis file , and read from it during chain initialzer ,and popoulate the native token as a key value pair on the blockchain . Other modules such as clp and peggy can read the value from this key value store. The best place for this would propably be the multistore for x/sifnode ? Also this can act as a placeholder for adding more such cofiguration in the future,

- Also as discussed before we need to finalze whats the difference between symbol and ticker , and remove whatever thats not needed ,this would help keep things uniform as well . For example clp uses c+ticker , and I think peggy uses c+symbol , which do end up being the same thing ,but might get confusing as the codebase increses in size

**Comment by utx0** [comment]
@ElliotFriedman can you confirm what is the symbol used in the smart contracts for the token sale? And how this relates? Thanks

**Comment by ElliotFriedman** [comment]
The token symbol of Rowan on etheruem should be eRowan because it is a cosmos native asset on top of ethereum according to this comment https://github.com/Sifchain/sifnode/issues/230#issuecomment-724131756. 

Not sure if that means that peggy will store it as eeRowan when it makes prophecy claims so will have to iron that out. It might end up being a situation where the symbol on etheruem is just rowan and then we prepend the 'e' to the symbol when we reference the token contract inside of the peggy smart contract code.

**Comment by utx0** [comment]
Ok just so everyone know as part of https://github.com/Sifchain/sifnode/releases/tag/monkey-bars-testnet-4 release we have changed the token symbol in the genesis to `rowan`  as can be seen in here: http://35.166.247.98:26657/genesis

For completeness;

1. Assert coming from native eth -> peggy -> sifchain will be prefixed with a `c`
2. Assert coming from native sifchain (cosmos) -> peggy -> eth will be prefixed with a `e`
3. Edge case is how we handle our native `rowan` token as this will be minted on eth first due to mainnet timelines. At this point I feel we will need to code this edge case into the code explicitly. More discussion needed here.

**Comment by Jedi2002** [comment]
@utx0 Can we also decide between the the two identifiers on the CLP side i.e ticker and symbol , it will make things less confusing going forward

**Comment by utx0** [comment]
@Jedi2002 sure thing. Lets open a new issue for that conversation though
