### ISSUE TITLE
GRPC siftool support for sifchain transactions (for load testing)

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2519]
Create python library to support communicating with sifnoded via grpc instead of command line.

This gives us more granular control over sequence number in order to invoke multiple tx at the same time

**Comment by pandaring2you** [comment]
Note: @Brando753 to chat with @jzvikart to see if GRPC support exists in siftool

**Comment by pandaring2you** [comment]
would need this to test 1K transactions from a single account

**Comment by pandaring2you** [comment]
@smartyalgo to sync with @jzvikart on support - should be top priority over siftool support for margin

**Comment by jzvikart** [comment]
I've created the stubs from files in `proto/sifnode/ethbridge/v1/tx.proto`. I open the gRPC channel to port 9090 but when I try to call `sifnode.ethbridge.v1.Msg.Lock()` I get this error:
```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown service sifnode.ethbridge.v1.Msg"
	debug_error_string = "{"created":"@1647338054.654116852","description":"Error received from peer ipv4:127.0.0.1:9090","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"unknown service sifnode.ethbridge.v1.Msg","grpc_status":12}"
```
It seems that the problem is only with `Msg` service. For example, `Query` appears to be working OK, I can call `GetBlacklist` and `CrosschainFeeConfig` over gRPC successfully.

According to @timlind transaction signing over gRPC isn't supported, so gRPC is only available for queries. Creating requests over other interfaces such as REST should be fine.

**Comment by pandaring2you** [comment]
Can go forward with this solution - possibly construct it in the command line.

**Comment by pandaring2you** [comment]
Proof of concept ETA next week.

**Comment by pandaring2you** [comment]
Michael done setting up load testing framework. Can now help out Jure with this task after merging current PRs

**Comment by pandaring2you** [comment]
issue: only one transaction works. might be that gas prices scale rapidly - will try increasing gas limit. checkout sifnode logs

**Comment by jzvikart** [comment]
Hi, proof of concept load test is working now. The problem I had before was not due to fees or `sequence`, but due to `account_number` - this field also has to be set correctly when signing a transaction (in other words, signature is a function of both `account_number` and `sequence`).

Test summary:

Given that:
- I have an environment with a single validator
- I'm sending 100 "ethbridge burn" transactions from sif account A to the eth account B
- I generate, sign and encode all transactions offline in advance using CLI
- I submit all of those 100 transactions via gRPC in `async` mode on a single thread

Then:
- The receiver ETH account balance is eventually increased by `100 * amount_per_tx`

Some observations:
- Approx. throughput of the bridge is ~0.19 TPS. According to what @banshee told me, I was expecting to see significantly higher rate, i.e. just one or two batches / O(1) time, but this still corresponds to roughly 1 transaction per block / O(n) time
- The receiver ETH balance changes in several irregular discrete "jumps", with jumps happening every 3-60s by the amount corresponding to 2-10 transactions
- The transactions have to be submitted via gRPC in order of ascending `sequence`. If they are not, they are not processed.
  - This implies that SDK treats them as FIFO and does not try to sort them internally.
  - This also means that any kind of multithreading doesn't make sense, at least not for a single account.
Generating and signing transactions is slow (~1 TPS), broadcasting is fast (~100 TPS)

From this point on, I want to scale up this test so that it would include more transactions and different accounts. For the current work in progress see branch `jure/2519`. Please let me know about any suggestions/ideas/feedback you have. Thanks!

**Comment by pandaring2you** [comment]
Basic load testing can be performed (burns) with this POC. Need feedback from @smartyalgo on the types of load tests that will be performed.
