### ISSUE TITLE
ProcessSignProphecy Potential DOS vulnerability 

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2865]
In x/ethbridge/keeper/keeper.go on line 334 in function ProcessSignProphecy, if CosmosSender is a field that the sender can fill in that is not their public address, then they can submit a signature when they should not have been able to which could jam the bridge up as the signature could be an invalid validator on ethereum. Add in a check to ensure that the CosmosSender is equal to the transaction signer to stop this behavior.

**Comment by Brando753** [comment]
Doesnt line 559 of ethbridge msgs.go already verify the signature of the cosmos sender? 
```go
// GetSigners defines whose signature is required
func (msg MsgSignProphecy) GetSigners() []sdk.AccAddress {
	cosmosSender, err := sdk.ValAddressFromBech32(msg.CosmosSender)
	if err != nil {
		panic(err)
	}

	return []sdk.AccAddress{sdk.AccAddress(cosmosSender)}
}
```
Should review before closing.

**Comment by Brando753** [comment]
Cosmos documentation suggests this would be verified on message send https://docs.cosmos.network/v0.45/core/transactions.html#signing-transactions

**Comment by Brando753** [comment]
@smartyalgo @Brando753 Reviewed this, we have no current test that checks SignProphecy from top-level down, we need coverage here before closing.

**Comment by pandaring2you** [comment]
@smartyalgo to prioritize before Denali remediations

**Comment by pandaring2you** [comment]
@juniuszhou - Would be great if you could think through how to implement test coverage here.

**Comment by juniuszhou** [comment]
Actually, I didn't see any special for MsgSignProphecy message compared with other messages. The signer is from "--from" flag, and the signature against the mssage is verified in the underlying system, instead of application like sifnode. So it is hard to get the raw tx data and verify them in sifnode unit test. 
I think the auditor may have some misunderstanding for this message MsgSignProphecy. The signature in MsgSignProphecy is the relayer use its ethereum private key to sign the prophecy, and all singatures will be verified in the smart contract, not in the cosmos. It means the signature in MsgSignProphecy has nothing to do with cosmosSender. 
I think we can explain to auditor and close the issue.

**Comment by banshee** [comment]
FYI, the signing check happens in

```
github.com/cosmos/cosmos-sdk@v0.43.0/x/auth/ante/sigverify.go
func (svd SigVerificationDecorator) AnteHandle(ctx sdk.Context, tx sdk.Tx, simulate bool, next sdk.AnteHandler) (newCtx sdk.Context, err error)
```

**Comment by pandaring2you** [comment]
Junius sent a draft PR - need to sync with @smartyalgo to determine if this is the right way to verify this issue

**Comment by pandaring2you** [comment]
@smartyalgo reviewing PR now, should be able to get this in with remaining elliot remediations

**Comment by pandaring2you** [comment]
ETA today. (technically fix has already been merged in the changes to elliot, Junius' PR is around testing the fix)

**Comment by pandaring2you** [comment]
Jure reviewing PR

**Comment by juniuszhou** [comment]
close it after #2984 merged.
