### ISSUE TITLE
Investigate why TPS is still only 1  (ethereum -> sifchain transactions)

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2977]
Related to #2845

**Comment by juniuszhou** [comment]
Executing the load test, the bottle neck is the max transactions in single message to Sifnode set as 5. we can consider increse it, then increase the tps. Since the size of each tx from lock/burn Ethereum is the fixed, we are safe to set a bigger number, will prepare a pr to add it as an argument for ebrelayer.

**Comment by juniuszhou** [comment]
close it after #3123 merged.

**Comment by pandaring2you** [comment]
Note: sync with Jure to determine if his work on load testing is now unblocked
