### ISSUE TITLE
Showing Information messages when adding liquidity asymmetrically

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#902]
**User Stroy:**
As a potential liquidity provider, I want to be informed when I am adding liquidity asymmetrically so I am aware of the potential ramifications of doing so.

**To do:**
- When a user is adding liquidity asymmetrically, we want to inform them of this action. 
- Rules:
--  IF a user has entered in amounts that are defined as asymmetric based on the current pool ratios, then we will:
--- a) The area of 'Prices after pooling and Pool Share': Outline this area in a red outline. Include an 'i' icon in the upper right-hand corner of this box. When a user clicks on this i, show a message that says: ''This is an asymmetric liquidity add. Please be aware of how this works by reading our documentation here.' See attached for design.

**Definition of Asymmetric Add:**
An asymmetric add is any liquidity add with a ratio of rowan to external asset that is different than the pool's ratio.

**Comment by caseyturnerarrington** [comment]
@thomasdavis initial findings:
- If it is the first time a user is adding to the pool, then we shouldn't show this message:
![Screen Shot 2021-03-05 at 4 21 35 PM](https://user-images.githubusercontent.com/45978818/110187912-0255e380-7de8-11eb-8970-7b1133b86a0b.png)
- It looks like we are missing the informational icon to click on.

**Comment by iverc** [comment]
@caseyturnerarrington @thomasdavis 
We should say that the pool share after liquidity is estimated and is subject to change.
I believe we should have a lot more explanation around that in terms of network impact (someone adds before you, so you have an unexpected result, or one of the LPs removes liquidity before you finish the tx, again, unexpected result), 
This is something we do not have any impact on, so the only thing we can do is make sure the user is aware in the most elegant and digestible way.



and on the other hand,  we should make it crystal clear of all dangers, possible losses, and impacts of asymmetric pooling. After switching to the new formula, values slip even more. So, as an example:

    - 100 rowan and 100 usdt in the pool, 1:1 ratio
    - new LP comes in and tries to add 200 rowan (or 200 USDT)
    - from the average user perspective, it looks like adding 50% of the pool because 100+100 = 200 in the pool already, and the user adds 200 more, so 200/400 is 50% from the user pov
    - in reality, adding 200 to either side results in 25% of the pool, and as a user, I get angry and would probably start to complain about that both privately and publicly) because I just pooled 200 coins and can only withdraw 100, the other 100 goes to the LP that was there before

The underlying behavior is quite complex and suggested actions/advice on how to avoid money loss (because it would require a lot of messaging with many assumptions, specific actions need to be taken, and this data could also have some real l shares going of one of the existing tables And again, I believe it is better not to show a prediction than show it and then be completely wrong (e.g. estimate is 70% result is 5%). On top of that, the negative effect of asymmetric swaps depends on the amount of the pooled tokens compared to the pool.

So, my suggestion for the pool share % goes as follows:
- we get the current slip adjustment (already have it in FE)
- we color the "25%" pool share text (only percentages) into:

1. Geen if the impact on the resulting pool share is insignificant (< 5% compared to what it was if you do that symmetrically, e.g. <5% money loss)
2. Yellow if the impact on the resulting pool share is noticeable (5-10% money loss)
3. Orange if the impact on the resulting pool share is severe (10-20% money loss)
4. Red if the impact on the resulting pool share is huge (20+% money loss)

@AustinoBombino please feel free to add your feedback as well

**Comment by caseyturnerarrington** [comment]
To summarize changes that we _should_ be doing for right now:
1) Color coding changes to the numbers within 'Prices after pooling & pool share' based upon Ivan's definition above.
2) Adjust the wording of 'Prices after pooling & pool share' to actually say 'Est. prices after pooling & pool share'.
3) If the color is yellow, orange, or red, include an 'i' icon in the upper right-hand corner of this box. When a user clicks on this i, show a message that says: ''This is an asymmetric liquidity add that has an estimated large impact on this pool. Please be aware of how this works by reading our documentation here.'

**Comment by thomasdavis** [comment]
PR ready for review -> https://github.com/Sifchain/sifnode/pull/896

**Comment by caseyturnerarrington** [comment]
@thomasdavis running into a weird case here. To recreate:
- I go into my existing liquidity pools.
- Click on manage and click add liquidity
- Click 'max' on the first input. 
- Observe.
See attached video for what I am seeing.

https://user-images.githubusercontent.com/45978818/111371635-12838380-8670-11eb-9012-cd6075910c0b.mov

**Comment by caseyturnerarrington** [comment]
<img width="1344" alt="Screen Shot 2021-03-17 at 6 53 01 AM" src="https://user-images.githubusercontent.com/45978818/111478563-925c2d00-8706-11eb-8fa0-d091527972ba.png">
1) @thomasdavis can we choose a different yellow color? I can hardly see the ! symbol at all here. (feel free to tap into @j-kappa for some help with the shading here)

2) Also, whats the exact logic you are using to determine when not to show the warning? Reason I ask is because if the slipAdjustment is '.0080' we are not showing any warning. I just want to make sure I update our documenation with the most accurate information.

**Comment by j-kappa** [comment]
@thomasdavis yeah that yellow isn't visible. Foregoing a redesign, a quick fix would be to replace it with #CAA93B 
Until I can get my hand on it preoperly.
